### ISSUE TITLE
写一个新的样式，以及其它一些问题

### ISSUE THREAD

**Issue by valloside** [Love-Kogasa/TouhouMobile#5]
写了一个新的样式，不怎么样但是至少**字**绝对能看清了。
~~或许太粉了~~
demo: https://thmobile.pages.dev/

![image](https://github.com/user-attachments/assets/1d8c5779-8682-4d5b-9ff2-3dfca70b9765)
![image](https://github.com/user-attachments/assets/0cc3fafb-0795-4d4d-80e6-c298eaeed74a)

具体修改见commit: https://github.com/valloside/TouhouMobile/commit/fcd635c2466a339293985d0557daf14394075704 ，如果觉得还行我可以开个pr。

### 关于游戏列表

![image](https://github.com/user-attachments/assets/e46a0424-b4de-4d54-9a8d-eb47d491a773)

我这边没做处理，因为我也不知道怎么搞比较好。
总之个人感觉手机上体验一般般 ~~，电脑上就是一坨勾使~~

### 关于隔壁issue

搞国际化，分页面是最佳的，放不同路径下，或者不同子域名下，对没有后端的静态网站都还行。
他说有部分模块加载不了，我不清楚是哪个文件在国外不能加载，如果他真用不了，那可能是兼容性问题。

至于版权，大部分游戏都是免费的吧，放个play链接之类的应该不难吧 ~~，难道说你们都用不了google play?~~

游戏文件放哪儿的问题，mega网盘对国外比较友好，对国内只需要魔法即可，没有注册门槛。或者干脆点，googledrive, onedrive走起，反正国内直接用lanzou就行了。但不管怎么样，放个网盘罢，~~放xx下载站是什么鬼？~~

**Comment by Love-Kogasa** [comment]
列表样式确实，backdrop-filter兼容性比较差，加上纯用样式语言弄得，所以确实挺屎的
不是连不上谷歌Play，是不知道哪个游戏是谷歌Play来的() 因为是网友给的

**Comment by Love-Kogasa** [comment]
隔壁那我英语不好，也许AI翻译有点问题~~问题很大~~
你看哪不太对你帮我再转达一下

**Comment by Love-Kogasa** [comment]
样式写的很不错呦w
我考虑考虑w 问问我们群群u

**Comment by valloside** [comment]
> 列表样式确实，backdrop-filter兼容性比较差，加上纯用样式语言弄得，所以确实挺屎的 不是连不上谷歌Play，是不知道哪个游戏是谷歌Play来的() 因为是网友给的

~~就这啊~~
咱不是有万能的包名查询吗？https://support.google.com/admob/answer/9972781?hl=zh-Hans

> 隔壁那我英语不好，也许AI翻译有点问题~问题很大~ 你看哪不太对你帮我再转达一下

他请求你给出邮箱交流，你好像没回复

**Comment by Love-Kogasa** [comment]
回复他了

**Comment by Love-Kogasa** [comment]
刚回复的() 当时没注意到

**Comment by LateDreamXD** [comment]
![df6ab183910e76982a3fc1cec7a3e090](https://github.com/user-attachments/assets/2a343bdc-332c-4909-8c52-00a3e48c9016)
