### ISSUE TITLE
新的游戏列表样式

### ISSUE THREAD

**Issue by valloside** [Love-Kogasa/TouhouMobile#6]
https://github.com/valloside/TouhouMobile/commit/9f12ddd1e95fff4b516bc1d18c292e83b3fecf67
↓↓↓此处应有一张GIF↓↓↓

![序列 01](https://github.com/user-attachments/assets/5d152f48-43b4-4536-962c-ba3e4a8e6d1c)
---
这样也挺好看的，

**Comment by Love-Kogasa** [comment]
好看w！

**Comment by valloside** [comment]
目前所有提交都可以直接合并进来，不过有个小问题就是，由于你的代码太不规范了，所以我对代码进行了大量重组，也就是说很多地方已经跟原来的代码没什么关系了

**Comment by Love-Kogasa** [comment]
确实，我代码写的比较骚。也比较乱( 偷懒导致的 )  
不过最近在想一个更新，到时候更新的时候一并加上  
你去THMobile-Inter创建一个分支，然后我明天弄上
谢谢啦w  
为什么大家都比我设计的好看w.  
咱—好—恨—啊—

**Comment by Love-Kogasa** [comment]
Ok了，然后我看了一下代码，可以  
原来navigator.clipboard要HTTPS吗，我localhost的lighttpd服务器能用(草草草

**Comment by Love-Kogasa** [comment]
Inter仓库我自己来吧w 我看你改的挺多的  
真的非常感谢，就不麻烦你了w
